version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  check:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint
          command: yarn lint
      - run:
          name: Format
          command: yarn format:check
      - run:
          name: Check dependencies
          command: yarn depcheck
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Run tests
          command: yarn test --ci
      - run:
          name: Ensure no changes to git-tracked files
          command: git --no-pager diff
  publish:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Update yarn.lock with new versions
          command: yarn
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Publish fern-openapi docker
          command: |
            projectVersion=$(git tag --points-at HEAD)
            yarn dockerTagVersion "$projectVersion"
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker tag fern-openapi:"$projectVersion" fernapi/fern-openapi:"$projectVersion"
            docker push fernapi/fern-openapi:"$projectVersion"

workflows:
  version: 2
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - check
          context:
            - docker-hub
